### ISSUE TITLE
Why my 'npm run build' command does work well?

### ISSUE THREAD

**Issue by chaozding** [SabakiHQ/Sabaki#324]
win10 64  

When I run 'npm run build', it is broken. I don't know why, does anybody come with this problem?

Below is the output of cmd  and 'npm-debug.log' :  

---

**output of cmd after run 'npm run build'**
```javascript
>npm run build

> sabaki@0.33.1 build E:\code\Sabaki
> npm run bundle && build --dir


> sabaki@0.33.1 bundle E:\code\Sabaki
> webpack --config webpack.prod.js --progress

Hash: dc692a2011e46e67effc
Version: webpack 3.10.0
Time: 4996ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  837 kB       0  [emitted]  [big]  main
   [2] ./src/modules/helper.js 2.7 kB {0} [built]
   [5] ./src/modules/gametree.js 12.3 kB {0} [built]
  [10] ./src/modules/fileformats/index.js 878 bytes {0} [built]
  [12] ./src/modules/board.js 15.7 kB {0} [built]
  [17] ./src/modules/gtp/index.js 1.34 kB {0} [built]
  [23] ./src/modules/dialog.js 1.5 kB {0} [built]
  [26] ./src/modules/fileformats/sgf.js 8.8 kB {0} [built]
  [48] ./src/modules/boardmatcher.js 4.82 kB {0} [built]
 [127] ./src/modules/gtp/command.js 386 bytes {0} [built]
 [128] ./src/modules/gtp/response.js 413 bytes {0} [built]
 [129] ./src/modules/gtp/controller.js 3.13 kB {0} [built]
 [269] ./src/modules/deadstones.js 9.14 kB {0} [built]
 [270] ./src/modules/enginesyncer.js 4.26 kB {0} [built]
 [271] ./src/modules/sound.js 1.2 kB {0} [built]
 [272] ./src/menu.js 20.8 kB {0} [built]
    + 258 hidden modules
  • electron-builder version=19.54.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist\electron-builder.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=1.7.10 appOutDir=dist\win-unpacked
Downloading tmp-17500-0-electron-v1.7.10-win32-x64.zip
Error: connect ETIMEDOUT 52.216.68.112:443
Error: connect ETIMEDOUT 52.216.68.112:443
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
From previous event:
    at Packager.packager.electronDownloader (E:\code\Sabaki\node_modules\electron-builder\src\builder.ts:291:12)
    at E:\code\Sabaki\node_modules\electron-builder-lib\src\packager\dirPackager.ts:53:21
    at next (native)
From previous event:
    at unpack (E:\code\Sabaki\node_modules\electron-builder-lib\out\packager\dirPackager.js:55:21)
    at unpackElectron (E:\code\Sabaki\node_modules\electron-builder-lib\src\packager\dirPackager.ts:27:10)
    at E:\code\Sabaki\node_modules\electron-builder-lib\src\platformPackager.ts:167:27
From previous event:
    at WinPackager.doPack (E:\code\Sabaki\node_modules\electron-builder-lib\out\platformPackager.js:283:11)
    at E:\code\Sabaki\node_modules\electron-builder-lib\src\platformPackager.ts:116:16
    at next (native)
From previous event:
    at WinPackager.pack (E:\code\Sabaki\node_modules\electron-builder-lib\out\platformPackager.js:201:11)
    at E:\code\Sabaki\node_modules\electron-builder-lib\src\packager.ts:361:24
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.doBuild (E:\code\Sabaki\node_modules\electron-builder-lib\out\packager.js:423:11)
    at E:\code\Sabaki\node_modules\electron-builder-lib\src\packager.ts:305:52
    at next (native)
    at E:\code\Sabaki\node_modules\graceful-fs\graceful-fs.js:99:16
    at E:\code\Sabaki\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
From previous event:
    at Packager._build (E:\code\Sabaki\node_modules\electron-builder-lib\out\packager.js:367:11)
    at E:\code\Sabaki\node_modules\electron-builder-lib\src\packager.ts:267:23
    at next (native)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (E:\code\Sabaki\node_modules\electron-builder-lib\out\packager.js:323:11)
    at E:\code\Sabaki\node_modules\electron-builder\src\builder.ts:310:40
    at next (native)
From previous event:
    at _build (E:\code\Sabaki\node_modules\electron-builder\out\builder.js:61:21)
    at build (E:\code\Sabaki\node_modules\electron-builder\src\builder.ts:280:10)
    at then (E:\code\Sabaki\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Object.args [as handler] (E:\code\Sabaki\node_modules\electron-builder\src\cli\cli.ts:49:33)
    at Object.runCommand (E:\code\Sabaki\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (E:\code\Sabaki\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (E:\code\Sabaki\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (E:\code\Sabaki\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! sabaki@0.33.1 build: `npm run bundle && build --dir`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sabaki@0.33.1 build script 'npm run bundle && build --dir'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sabaki package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run bundle && build --dir
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sabaki
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sabaki
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\code\Sabaki\npm-debug.log
```
---

**npm-debug.log:**
```javascript
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle sabaki@0.33.1~prebuild: sabaki@0.33.1
6 silly lifecycle sabaki@0.33.1~prebuild: no script for prebuild, continuing
7 info lifecycle sabaki@0.33.1~build: sabaki@0.33.1
8 verbose lifecycle sabaki@0.33.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle sabaki@0.33.1~build: PATH: 

...

10 verbose lifecycle sabaki@0.33.1~build: CWD: E:\code\Sabaki
11 silly lifecycle sabaki@0.33.1~build: Args: [ '/d /s /c', 'npm run bundle && build --dir' ]
12 silly lifecycle sabaki@0.33.1~build: Returned: code: 1  signal: null
13 info lifecycle sabaki@0.33.1~build: Failed to exec build script
14 verbose stack Error: sabaki@0.33.1 build: `npm run bundle && build --dir`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid sabaki@0.33.1
16 verbose cwd E:\code\Sabaki
17 error Windows_NT 10.0.16299
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error sabaki@0.33.1 build: `npm run bundle && build --dir`
22 error Exit status 1
23 error Failed at the sabaki@0.33.1 build script 'npm run bundle && build --dir'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the sabaki package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run bundle && build --dir
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs sabaki
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls sabaki
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by ohyou** [comment]
```
Downloading tmp-17500-0-electron-v1.7.10-win32-x64.zip
Error: connect ETIMEDOUT 52.216.68.112:443
Error: connect ETIMEDOUT 52.216.68.112:443
```

As per the error message, it would appear that you can't connect to the servers in order to download the latest electron build.

**Comment by yishn** [comment]
I'm closing this due to inactivity.
