### ISSUE TITLE
Error: Cannot create BrowserWindow before app is ready 

### ISSUE THREAD

**Issue by CamusLee** [SabakiHQ/Sabaki#489]
Sabaki v0.41.0

Something weird happened. Sabaki will shut itself down. If possible, please report this on Sabaki’s repository on GitHub.

Error: Cannot create BrowserWindow before app is ready
    at newWindow (/Applications/Sabaki.app/Contents/Resources/app.asar/src/main.js:15:18)
    at App.app.on (/Applications/Sabaki.app/Contents/Resources/app.asar/src/main.js:183:29)
    at App.emit (events.js:182:13)

**Comment by yishn** [comment]
Could be related to #392. It worked fine before, right? Do you know what you've changed?

**Comment by yishn** [comment]
I'm closing this due to inactivity
