### ISSUE TITLE
featire request: provide portable file.

### ISSUE THREAD

**Issue by ivysrono** [SabakiHQ/Sabaki#657]
As I know, electron-builder has this feature.
this may work with #656

**Comment by yishn** [comment]
Maybe you can help us set up this feature?

**Comment by ivysrono** [comment]
I'm not good at electron and webpack, just try:

"build":
```
    "win": {
      "target": "portable"
    },
```

"scripts": 
```
    "p": "npm run bundle && electron-builder --win",
```

Get `Sabaki 0.50.1.exe` and launch error:
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: Cannot find module '@sabaki/i18n'
Require stack:
- C:\Users\xx\AppData\Local\Temp\1ZDG19Esb5o7IvwBezRH2Ex47V4\resources\app.asar\src\i18n.js
- C:\Users\xx\AppData\Local\Temp\1ZDG19Esb5o7IvwBezRH2Ex47V4\resources\app.asar\src\main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7595:16)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\xx\AppData\Local\Temp\1ZDG19Esb5o7IvwBezRH2Ex47V4\resources\app.asar\src\i18n.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
```

**Comment by yishn** [comment]
We didn't include @sabaki/i18n in the build bundle; it should work fine now.

**Comment by ivysrono** [comment]
#659

**Comment by ivysrono** [comment]
discussion:
I have writen a vbs file to package sabaki fast:
```
command_chinesenpm = "npm --registry https://registry.npm.taobao.org install"
command_disturl = "npm config set disturl https://npm.taobao.org/mirrors/atom-shell"
command_electron = "npm config set ELECTRON_MIRROR https://cdn.npm.taobao.org/dist/electron/"

LangId = CreateObject("wscript.Shell").RegRead("HKEY_CURRENT_USER\Control Panel\International\Locale")

If LangId = "00000804" Then ' Accelerate and simplify for Chinese Mainland users.
    CreateObject("WScript.Shell").Run command_electron, 1, true
    CreateObject("WScript.Shell").Run command_disturl, 1, true
    CreateObject("WScript.Shell").Run command_chinesenpm, 1, true
Else
    CreateObject("WScript.Shell").Run "npm install", 1, true
End If

'CreateObject("WScript.Shell").Run "npm run watch", 1, true
'CreateObject("WScript.Shell").Run "npm start", 0
'CreateObject("WScript.Shell").Run "npm run build", 1, true
'00000804 Chinese (PRC)
'00000404 Chinese (Taiwan)
'00000c04 Chinese (Hong Kong SAR, PRC)
'00001004 Chinese (Singapore)

'CreateObject("WScript.Shell").Run "npm run dist:portable32", 1
CreateObject("WScript.Shell").Run "npm run dist:portable64", 1
'CreateObject("WScript.Shell").Run "npm run dist:win32", 1
'CreateObject("WScript.Shell").Run "npm run dist:win64", 1
'CreateObject("WScript.Shell").Run "npm run dist:linux", 1
'CreateObject("WScript.Shell").Run "npm run dist:macos", 1
```
NPM and github are so slow in China, that's why we need to set mirror.
Would you merge it if I create one PR?
If yes, should I delete the LangId check?
If no, would you like to add `*.vbs` in `.gitignore`?

**Comment by yishn** [comment]
If we'd like to provide such a script, we need to make it cross-platform, and not Windows only. Maybe we should link to the instructions? If you just want to add `.vbs` to `.gitignore`, feel free to add it in your existing PR.

**Comment by ivysrono** [comment]
Thanks, done.
