### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by uhuntu** [SabakiHQ/Sabaki#820]
```
hunt@hunt-OptiPlex-7071:~/work/Sabaki$ npm run build

> sabaki@0.52.0 build
> npm run bundle && electron-builder --dir


> sabaki@0.52.0 bundle
> webpack --mode production

Hash: 0927ab07d95d811fa33f
Version: webpack 4.46.0
Time: 1271ms
Built at: 08/27/2021 3:15:32 PM
    Asset     Size  Chunks             Chunk Names
bundle.js  936 KiB       0  [emitted]  main
Entrypoint main = bundle.js
  [1] ./src/modules/sabaki.js + 2 modules 86.6 KiB {0} [built]
      | ./src/modules/sabaki.js 74.6 KiB [built]
      | ./src/modules/enginesyncer.js 10.7 KiB [built]
      | ./src/modules/sound.js 1.19 KiB [built]
  [2] ./src/modules/helper.js 3.85 KiB {0} [built]
  [3] ./src/i18n.js 2.11 KiB {0} [built]
  [7] ./src/modules/gametree.js 9.13 KiB {0} [built]
  [8] ./src/modules/dialog.js 1.38 KiB {0} [built]
  [9] external "path" 42 bytes {0} [built]
 [10] external "fs" 42 bytes {0} [built]
 [13] external "events" 42 bytes {0} [built]
 [14] ./src/modules/gobantransformer.js 3.34 KiB {0} [built]
 [15] external "electron" 42 bytes {0} [built]
 [20] ./src/modules/gtplogger.js 3.14 KiB {0} [built]
 [25] ./src/modules/fileformats/index.js + 4 modules 16.4 KiB {0} [built]
      | ./src/modules/fileformats/index.js 933 bytes [built]
      | ./src/modules/fileformats/sgf.js 665 bytes [built]
      | ./src/modules/fileformats/ngf.js 4.91 KiB [built]
      | ./src/modules/fileformats/gib.js 5.63 KiB [built]
      | ./src/modules/fileformats/ugf.js 4.27 KiB [built]
[131] ./src/menu.js 28.9 KiB {0} [built]
[214] external "require(\"@sabaki/i18n\")" 42 bytes {0} [built]
[416] ./src/components/App.js + 38 modules 203 KiB {0} [built]
      | ./src/modules/gamesort.js 2.02 KiB [built]
      |     + 38 hidden modules
    + 409 hidden modules
Error: Cannot find module 'fs/promises'
Require stack:
- /home/hunt/work/Sabaki/node_modules/builder-util/out/fs.js
- /home/hunt/work/Sabaki/node_modules/builder-util/out/util.js
- /home/hunt/work/Sabaki/node_modules/electron-builder/out/cli/cli.js
- /home/hunt/work/Sabaki/node_modules/electron-builder/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hunt/work/Sabaki/node_modules/builder-util/src/fs.ts:4:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/hunt/work/Sabaki/node_modules/builder-util/src/util.ts:24:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

```

**Comment by apetresc** [comment]
Did you do `npm install` first?

**Comment by uhuntu** [comment]
Yes

**Comment by apetresc** [comment]
My other guess is that you're on a very old version of Node.js (12 or earlier). What is the output of `node --version` ?

**Comment by uhuntu** [comment]
Yes, you are right, after update node by ubuntu snap to 14, then it work, thanks.
